variables:
  MONO_VERSION: 6_8_0
  XCODE_VERSION: 11.3
  NETCORE_VERSION: '3.1.x'

name: 2.2.0.$(Build.BuildId)

trigger:
  branches:
    include:
      - master 
  paths:
    exclude:
      - README.md
      - images/*
      - ci-pancakes.yml
      - cd-pancakes.yml

pool:
  name: Hosted VS2017
  demands: msbuild

jobs:

  - job: build_windows
    displayName: Build Windows Library
    pool:
      vmImage: windows-2019
    steps:
      - task: MSBuild@1
        displayName: Build
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'
          clean: true

      - task: MSBuild@1
        displayName: Pack NuGets Beta
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/t:Pack /p:PackageVersion=$(Build.BuildNumber)-beta /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)/beta"'

      - task: MSBuild@1
        displayName: Pack NuGets Final
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/t:Pack /p:PackageVersion=$(Build.BuildNumber) /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)/final"'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(build.sourcesdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
        
  - job: build_macos
    displayName: Build macOS Library
    pool:
      vmImage: macos-10.14
    steps:
    
      # make sure to select the correct Xamarin and mono
      - bash: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh $(MONO_VERSION)
        displayName: Switch to the latest Xamarin SDK
      - bash: echo '##vso[task.setvariable variable=MD_APPLE_SDK_ROOT;]'/Applications/Xcode_$(XCODE_VERSION).app;sudo xcode-select --switch /Applications/Xcode_$(XCODE_VERSION).app/Contents/Developer
        displayName: Switch to the latest Xcode

      # restore, build and pack the packages
      - task: UseDotNet@2
        displayName: 'Use .Net Core sdk'
        inputs:
          version: $(NETCORE_VERSION)
          includePreviewVersions: false
          
      - task: MSBuild@1
        displayName: Build
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/restore /t:Build /p:ContinuousIntegrationBuild=true /p:Deterministic=false'
          clean: true

      - task: MSBuild@1
        displayName: Pack NuGets Beta
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/t:Pack /p:PackageVersion=$(NugetPackageVersion) /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)/beta"'

      - task: MSBuild@1
        displayName: Pack NuGets Final
        inputs:
          solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
          configuration: Release
          msbuildArguments: '/t:Pack /p:PackageVersion=$(NugetPackageVersion) /p:PackageOutputPath="$(Build.ArtifactStagingDirectory)/final"'

      - task: CopyFiles@2
        displayName: 'Copy Files to: $(build.artifactstagingdirectory)'
        inputs:
          SourceFolder: '$(build.sourcesdirectory)'
          Contents: '**\bin\$(BuildConfiguration)\**\*.nupkg'
          TargetFolder: '$(build.artifactstagingdirectory)'

      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'
