# Defines that a commit to the master branch should trigger this build
trigger:
  branches:
    include:
      - master 
  paths:
    exclude:
      - README.md
      - images/*
      - ci-build-pipeline.yml
      - cd-build-pipeline.yml

# Defines that PRs against this branch should also trigger this build
pr:
- master

pool:
  name: Hosted VS2017
  demands: msbuild

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.9.3'
  inputs:
    versionSpec: 4.9.3

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: 'src/**/*.sln'

- task: MSBuild@1
  displayName: 'Build solution'
  inputs:
    solution: src/Xamarin.Forms.PancakeView.Multi/Xamarin.Forms.PancakeView.Multi.csproj
    msbuildArguments: '/t:restore;build /p:PackageOutputPath=$(build.artifactstagingdirectory)'
    clean: true
